customhost = "wolfpack-markethub.cksrdsj5psau.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "Bait3273"
customdb = "employeeDB"
custombucket = "wolfpack-mhub-data"
customregion = "us-east-1"
